testing env scope

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -9,7 +9,6 @@ jobs:
     name: linux-cp${{ matrix.python-version }}-${{ matrix.OPTIONS_NAME }}
     runs-on: ubuntu-20.04
     env:
-        BUILD_DOCS: 1
         TEST_EXAMPLES: 0
         SKIMAGE_TEST_STRICT_WARNINGS_GLOBAL: 0
 
@@ -17,14 +16,14 @@ jobs:
       # Ensure that a wheel builder finishes even if another fails
       fail-fast: false
       matrix:
-        python-version: [3.8, 3.9, '3.10']
+        python-version: [3.9]  # 3.8, 3.9, '3.10']
         PIP_FLAGS: [""]
         MINIMUM_REQUIREMENTS: [0]
         QT: ["PyQt5"]
         WITH_PYSIDE: [0]
         BUILD_DOCS: [1]
         PYTHONOPTIMIZE: [0]
-        TEST_EXAMPLES: [0]
+#        TEST_EXAMPLES: [0]
         OPTIONAL_DEPS: [0]
         OPTIONS_NAME: ["default"]
         INSTALL_FROM_SDIST: [0]
@@ -104,11 +103,11 @@ jobs:
             QT: ${{ matrix.QT }}
             WITH_PYSIDE: ${{ matrix.WITH_PYSIDE }}
             BUILD_DOCS: ${{ matrix.BUILD_DOCS }}
-            TEST_EXAMPLES: ${{ matrix.TEST_EXAMPLES }}
+#            TEST_EXAMPLES: ${{ matrix.TEST_EXAMPLES }}
             OPTIONAL_DEPS: ${{ matrix.OPTIONAL_DEPS }}
             EAGER_IMPORT: ${{ matrix.EAGER_IMPORT }}
             INSTALL_FROM_SDIST: ${{ matrix.INSTALL_FROM_SDIST }}
-            SKIMAGE_TEST_STRICT_WARNINGS_GLOBAL: ${{ matrix.SKIMAGE_TEST_STRICT_WARNINGS_GLOBAL }}
+#             SKIMAGE_TEST_STRICT_WARNINGS_GLOBAL: ${{ matrix.SKIMAGE_TEST_STRICT_WARNINGS_GLOBAL }}
         run: |
             echo $PIP_FLAGS
             pip install $PIP_FLAGS -r requirements/test.txt
@@ -130,78 +129,78 @@ jobs:
           asv check -v -E existing
 
 
-  test_skimage_macos:
-    name: macos-cp${{ matrix.python-version }}
-    runs-on: macos-latest
+  # test_skimage_macos:
+  #   name: macos-cp${{ matrix.python-version }}
+  #   runs-on: macos-latest
 
-    strategy:
-      # Ensure that a wheel builder finishes even if another fails
-      fail-fast: false
-      matrix:
-        python-version: [3.8, 3.9, '3.10']
-        QT: ["PyQt5"]
-        BUILD_DOCS: [1]
-        TEST_EXAMPLES: [0]
-        OPTIONAL_DEPS: [1]
-        OPTIONS_NAME: ["default"]
-        include:
-          - python-version: 3.9
-            OPTIONAL_DEPS: 0
-          - python-version: '3.10'
-            OPTIONAL_DEPS: 0
-        exclude:
-          - python-version: 3.8
-            OPTIONAL_DEPS: 1
-          # Problem with SimpleITK and py 3.9
-          - python-version: 3.9
-            OPTIONAL_DEPS: 1
-          # a number of optional deps don't yet have Python 3.10 wheels
-          - python-version: '3.10'
-            OPTIONAL_DEPS: 1
-    env:
-        BUILD_DOCS: 1
-        TEST_EXAMPLES: 0
-        CC: /usr/bin/clang
-        CXX: /usr/bin/clang++
-        CPPFLAGS: "-Xpreprocessor -fopenmp"
-        CFLAGS: "-Wno-implicit-function-declaration -I/usr/local/opt/libomp/include"
-        CXXFLAGS: "-I/usr/local/opt/libomp/include"
-        LDFLAGS: "-Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
+  #   strategy:
+  #     # Ensure that a wheel builder finishes even if another fails
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: [3.8, 3.9, '3.10']
+  #       QT: ["PyQt5"]
+  #       BUILD_DOCS: [1]
+  #       TEST_EXAMPLES: [0]
+  #       OPTIONAL_DEPS: [1]
+  #       OPTIONS_NAME: ["default"]
+  #       include:
+  #         - python-version: 3.9
+  #           OPTIONAL_DEPS: 0
+  #         - python-version: '3.10'
+  #           OPTIONAL_DEPS: 0
+  #       exclude:
+  #         - python-version: 3.8
+  #           OPTIONAL_DEPS: 1
+  #         # Problem with SimpleITK and py 3.9
+  #         - python-version: 3.9
+  #           OPTIONAL_DEPS: 1
+  #         # a number of optional deps don't yet have Python 3.10 wheels
+  #         - python-version: '3.10'
+  #           OPTIONAL_DEPS: 1
+  #   env:
+  #       BUILD_DOCS: 1
+  #       TEST_EXAMPLES: 0
+  #       CC: /usr/bin/clang
+  #       CXX: /usr/bin/clang++
+  #       CPPFLAGS: "-Xpreprocessor -fopenmp"
+  #       CFLAGS: "-Wno-implicit-function-declaration -I/usr/local/opt/libomp/include"
+  #       CXXFLAGS: "-I/usr/local/opt/libomp/include"
+  #       LDFLAGS: "-Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
 
-    steps:
-      - name: Checkout scikit-image
-        uses: actions/checkout@v1
+  #   steps:
+  #     - name: Checkout scikit-image
+  #       uses: actions/checkout@v1
 
-      - name: Setup Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version}}
+  #     - name: Setup Python
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: ${{ matrix.python-version}}
 
-      - name: OSX configuration
-        run: |
-            # OpenMP is not present on macOS by default
-            set -ex
-            brew install libomp
+  #     - name: OSX configuration
+  #       run: |
+  #           # OpenMP is not present on macOS by default
+  #           set -ex
+  #           brew install libomp
 
-      - name: Build package
-        run: |
-            set -ex
-            source tools/github/before_install.sh
-            python setup.py sdist
-            pip install -vv --no-build-isolation -e .;
+  #     - name: Build package
+  #       run: |
+  #           set -ex
+  #           source tools/github/before_install.sh
+  #           python setup.py sdist
+  #           pip install -vv --no-build-isolation -e .;
 
-      - name: Run tests
-        run: |
-            pip install $PIP_FLAGS -r requirements/test.txt
-            export MPL_DIR=`python -c 'import matplotlib; print(matplotlib.get_configdir())'`
-            mkdir -p ${MPL_DIR}
-            touch ${MPL_DIR}/matplotlibrc
-            if [[ "${OPTIONAL_DEPS}" == "1" ]]; then
-                pip install -r ./requirements/optional.txt
-                pip install -r ./requirements/extras.txt
-            fi
-            source tools/github/script.sh
+  #     - name: Run tests
+  #       run: |
+  #           pip install $PIP_FLAGS -r requirements/test.txt
+  #           export MPL_DIR=`python -c 'import matplotlib; print(matplotlib.get_configdir())'`
+  #           mkdir -p ${MPL_DIR}
+  #           touch ${MPL_DIR}/matplotlibrc
+  #           if [[ "${OPTIONAL_DEPS}" == "1" ]]; then
+  #               pip install -r ./requirements/optional.txt
+  #               pip install -r ./requirements/extras.txt
+  #           fi
+  #           source tools/github/script.sh
 
-      - name: Check benchmarks
-        run: |
-          asv check -v -E existing
+  #     - name: Check benchmarks
+  #       run: |
+  #         asv check -v -E existing
